# Generated by Django 4.2.11 on 2025-08-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0015_historicalcommon'),
        ('users', '0012_historicalusers_historicalroles_historicalbranch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_historicalcustomergroup_historicalcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('common_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='globalapp.common')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('father_husband_name', models.CharField(max_length=150, verbose_name='Father/Husband Name')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('secondary_mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Mobile Number')),
                ('nid_front', models.TextField(blank=True, max_length=100, null=True, verbose_name='NID Front')),
                ('nid_back', models.TextField(blank=True, max_length=100, null=True, verbose_name='NID Back')),
                ('nid_number', models.CharField(max_length=30, verbose_name='NID Number')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('house_photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='House Photo')),
                ('utility_bill', models.TextField(blank=True, max_length=100, null=True, verbose_name='Electric/Water Bill')),
                ('house_remark_bn', models.TextField(blank=True, null=True, verbose_name='House Remark (Bangla)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.branch', verbose_name='Branch Name')),
                ('guarantor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'Guarantor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Guarantor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Customer',
                'verbose_name_plural': 'historical Customers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('father_husband_name', models.CharField(max_length=150, verbose_name='Father/Husband Name')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('secondary_mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Mobile Number')),
                ('nid_front', models.ImageField(blank=True, null=True, upload_to='customer/nid/front/', verbose_name='NID Front')),
                ('nid_back', models.ImageField(blank=True, null=True, upload_to='customer/nid/back/', verbose_name='NID Back')),
                ('nid_number', models.CharField(max_length=30, verbose_name='NID Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer/photos/', verbose_name='Photo')),
                ('house_photo', models.ImageField(blank=True, null=True, upload_to='customer/house_photos/', verbose_name='House Photo')),
                ('utility_bill', models.ImageField(blank=True, null=True, upload_to='customer/bills/', verbose_name='Electric/Water Bill')),
                ('house_remark_bn', models.TextField(blank=True, null=True, verbose_name='House Remark (Bangla)')),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.branch', verbose_name='Branch Name')),
                ('guarantor', models.ForeignKey(blank=True, limit_choices_to={'type': 'Guarantor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Guarantor')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['full_name'],
            },
            bases=('globalapp.common',),
        ),
    ]
