# Generated by Django 4.2.11 on 2025-08-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_customer_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Location URL'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Location URL'),
        ),
    ]
