# Generated by Django 4.2.11 on 2025-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_location_url_historicalcontact_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='location_url',
        ),
        migrations.AddField(
            model_name='customer',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Location URL'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Location URL'),
        ),
    ]
