# Generated by Django 4.2.11 on 2025-09-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_historicalcontact_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcustomergroup',
            name='updated_at',
        ),
    ]
