# Generated by Django 4.2.11 on 2025-09-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_historicalcontact_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcustomergroup',
            name='updated_at',
        ),
    ]
