# Generated by Django 4.2.11 on 2025-09-19 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0012_remove_historicalcontact_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='customer_group',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='customer_group',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='contacts.customergroup', verbose_name='Customer Group'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='customer_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customergroup', verbose_name='Customer Group'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Guarantor', 'Guarantor')], max_length=20, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer', verbose_name='Group Leader User'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Guarantor', 'Guarantor')], max_length=20, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='historicalcustomergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customer', verbose_name='Group Leader User'),
        ),
        migrations.CreateModel(
            name='HistoricalDailySaving',
            fields=[
                ('common_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='globalapp.common')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField(verbose_name='Saving Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('saving_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'historical daily saving',
                'verbose_name_plural': 'historical daily savings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DailySaving',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('date', models.DateField(verbose_name='Saving Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('saving_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_savings', to='contacts.customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('saving_customer', 'date')},
            },
            bases=('globalapp.common',),
        ),
    ]
