# Generated by Django 4.2.11 on 2025-09-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0013_remove_contact_customer_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysaving',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Saving', 'verbose_name_plural': 'Daily Savings'},
        ),
        migrations.AlterModelOptions(
            name='historicaldailysaving',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Daily Saving', 'verbose_name_plural': 'historical Daily Savings'},
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customergroup'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='customer_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customergroup'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Account Balance'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Account Balance'),
        ),
        migrations.AlterField(
            model_name='historicalcustomergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customer'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('transaction_type', models.CharField(choices=[('SAVING', 'Daily Saving'), ('LOAN', 'Loan'), ('WITHDRAWAL', 'Withdrawal'), ('INTEREST', 'Interest'), ('FEE', 'Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contacts.customer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('common_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='globalapp.common')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('transaction_type', models.CharField(choices=[('SAVING', 'Daily Saving'), ('LOAN', 'Loan'), ('WITHDRAWAL', 'Withdrawal'), ('INTEREST', 'Interest'), ('FEE', 'Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer_ref', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transaction',
                'verbose_name_plural': 'historical Transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
