# Generated by Django 4.2.11 on 2025-09-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_alter_dailysaving_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customergroup',
            old_name='group_leader_user',
            new_name='group_leader',
        ),
        migrations.RenameField(
            model_name='historicalcustomergroup',
            old_name='group_leader_user',
            new_name='group_leader',
        ),
    ]
