# Generated by Django 4.2.11 on 2025-09-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0015_rename_group_leader_user_customergroup_group_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldailysaving',
            name='common_ptr',
        ),
        migrations.RemoveField(
            model_name='historicaldailysaving',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldailysaving',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldailysaving',
            name='saving_customer',
        ),
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='common_ptr',
        ),
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='customer_ref',
        ),
        migrations.RemoveField(
            model_name='historicaltransaction',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='common_ptr',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_ref',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_group',
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='group_leader',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='customer_group',
        ),
        migrations.RemoveField(
            model_name='historicalcustomergroup',
            name='group_leader',
        ),
        migrations.AddField(
            model_name='customergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Group Leader User'),
        ),
        migrations.AddField(
            model_name='historicalcustomergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Group Leader User'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customergroup', verbose_name='Customer Group'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Guarantor', 'Guarantor')], max_length=20, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='customer_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customergroup', verbose_name='Customer Group'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Guarantor', 'Guarantor')], max_length=20, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='DailySaving',
        ),
        migrations.DeleteModel(
            name='HistoricalDailySaving',
        ),
        migrations.DeleteModel(
            name='HistoricalTransaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
