# Generated by Django 4.2.11 on 2025-09-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_remove_historicaldailysaving_common_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Guarantor', 'Guarantor')], max_length=20, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer', verbose_name='Group Leader User'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Guarantor', 'Guarantor')], max_length=20, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='historicalcustomergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customer', verbose_name='Group Leader User'),
        ),
    ]
