# Generated by Django 4.2.11 on 2025-09-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_alter_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customergroup', verbose_name='Customers Group'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='customer_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customergroup', verbose_name='Customers Group'),
        ),
    ]
