# Generated by Django 4.2.11 on 2025-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_customer_customer_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='contacts.customer', verbose_name='Group Members'),
        ),
    ]
