# Generated by Django 4.2.11 on 2025-09-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_users_profile_picture'),
        ('contacts', '0019_customergroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.area', verbose_name='Area Name'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='customer_group_area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.area', verbose_name='Area Name'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='customer_group_branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.branch', verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='area_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.area', verbose_name='Area Name'),
        ),
        migrations.AddField(
            model_name='historicalcustomergroup',
            name='customer_group_area_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.area', verbose_name='Area Name'),
        ),
        migrations.AddField(
            model_name='historicalcustomergroup',
            name='customer_group_branch_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.branch', verbose_name='Branch Name'),
        ),
    ]
