# Generated by Django 4.2.11 on 2025-10-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_customer_area_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='group_leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_groups', to='contacts.customer', verbose_name='Group Leader User'),
        ),
    ]
