# Generated by Django 4.2.11 on 2025-10-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_users_profile_picture'),
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        ('contacts', '0021_alter_customergroup_group_leader_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('behaviour_type', models.JSONField(blank=True, default=list, null=True)),
                ('customer_type_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_type', to='users.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Type',
                'ordering': ['name'],
            },
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='customer',
            name='coustomer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customertype', verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='coustomer_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customertype', verbose_name='Customer Type'),
        ),
    ]
