# Generated by Django 4.2.11 on 2025-10-27 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0022_customertype_customer_coustomer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Received By'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='received_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Received By'),
        ),
    ]
