# Generated by Django 4.2.11 on 2024-06-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
