# Generated by Django 4.2.11 on 2024-08-30 20:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_roles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profie_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
