# Generated by Django 4.2.11 on 2024-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_phone_number_users_profie_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
