# Generated by Django 4.2.11 on 2024-09-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='profie_picture',
            new_name='profile_picture',
        ),
    ]
