# Generated by Django 4.2.11 on 2024-09-15 07:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_profie_picture_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
