# Generated by Django 4.2.11 on 2025-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='nid/back/'),
        ),
        migrations.AddField(
            model_name='users',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='nid/front/'),
        ),
        migrations.AddField(
            model_name='users',
            name='nid_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
