# Generated by Django 4.2.11 on 2025-08-13 00:03

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_branch_users_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=400, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='users',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='nid/back/', verbose_name='NID Back Image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='nid/front/', verbose_name='NID Front Image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nid_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NID Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.roles', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Username'),
        ),
    ]
