# Generated by Django 4.2.11 on 2025-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_historicalusers_historicalroles_historicalbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbranch',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalroles',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
