# Generated by Django 4.2.11 on 2025-09-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_historicalbranch_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbranch',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalroles',
            name='updated_at',
        ),
    ]
