# Generated by Django 4.2.11 on 2025-09-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_historicalbranch_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbranch',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalroles',
            name='updated_at',
        ),
    ]
