# Generated by Django 4.2.11 on 2025-09-15 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_historicalarea_area_branch_total_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='historicalarea',
            name='parent_branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_staf',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='AreaStaf'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Area Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='total_area',
            field=models.ManyToManyField(blank=True, related_name='branches', to='users.area', verbose_name='TotalArea'),
        ),
        migrations.AlterField(
            model_name='historicalarea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Area Name'),
        ),
    ]
