# Generated by Django 4.2.11 on 2025-09-16 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_area_parent_branch_historicalarea_parent_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='area',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='users',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userss_area', to='users.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_staf',
            field=models.ManyToManyField(blank=True, related_name='staffed_areas', to=settings.AUTH_USER_MODEL, verbose_name='AreaStaf'),
        ),
    ]
