# Generated by Django 4.2.11 on 2025-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_historicalusers_area_users_area_alter_area_area_staf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='Profile Picture'),
        ),
    ]
