# Generated by Django 4.2.11 on 2025-10-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        ('users', '0021_alter_users_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiBranch',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('title', models.CharField(max_length=300)),
                ('multi_branch', models.ManyToManyField(to='users.branch')),
            ],
            options={
                'verbose_name': 'MultiBranch',
                'verbose_name_plural': 'MultiBranch',
            },
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='HistoricalMultiBranch',
            fields=[
                ('common_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='globalapp.common')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.CharField(max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical MultiBranch',
                'verbose_name_plural': 'historical MultiBranch',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='users',
            name='mult_branch',
            field=models.ManyToManyField(blank=True, null=True, related_name='userss_mult_branch', to='users.multibranch', verbose_name='MultiBranch'),
        ),
    ]
