# Generated by Django 4.2.11 on 2025-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_multibranch_historicalmultibranch_users_mult_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='customer_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='customer_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
