# Generated by Django 4.2.11 on 2025-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_historicalusers_customer_group_users_customer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mult_branch',
            field=models.ManyToManyField(blank=True, related_name='userss_mult_branch', to='users.multibranch', verbose_name='MultiBranch'),
        ),
    ]
