# Generated by Django 4.2.11 on 2026-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_historicalusers_nid_back_alter_users_nid_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='nid_back',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='NID Back Images'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='nid/back/', verbose_name='NID Back Images'),
        ),
    ]
