# Generated by Django 4.2.11 on 2024-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0002_basebeneficariesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebeneficariesmodel',
            name='nid_back',
            field=models.ImageField(default='car.jpg', upload_to='nid/'),
        ),
        migrations.AlterField(
            model_name='basebeneficariesmodel',
            name='nid_front',
            field=models.ImageField(default='car.jpg', upload_to='nid/'),
        ),
        migrations.AlterField(
            model_name='basebeneficariesmodel',
            name='profile_picture',
            field=models.ImageField(default='car.jpg', upload_to='profile_pictures/'),
        ),
    ]
