# Generated by Django 4.2.11 on 2024-04-27 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0003_alter_basebeneficariesmodel_nid_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebeneficariesmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='basebeneficariesmodel',
            name='nid_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nid_number', message='NID number must contain only numeric values.', regex='^[0-9]*$')]),
        ),
    ]
