# Generated by Django 4.2.11 on 2024-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0005_alter_basebeneficariesmodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebeneficariesmodel',
            name='nid_back',
            field=models.ImageField(default='nid/nid_back.jpeg', upload_to='nid/'),
        ),
        migrations.AlterField(
            model_name='basebeneficariesmodel',
            name='nid_front',
            field=models.ImageField(default='nid/nid_front.jpeg', upload_to='nid/'),
        ),
    ]
