# Generated by Django 4.2.11 on 2024-05-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0006_alter_basebeneficariesmodel_nid_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('title', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('favicon', models.ImageField(upload_to='logo/')),
                ('base_color', models.CharField(default='#ffffff', max_length=10)),
                ('primary_color', models.CharField(default='#ff8100', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('globalapp.common', models.Model),
        ),
    ]
