# Generated by Django 4.2.11 on 2024-05-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0007_softwareasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfigure',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('password', models.CharField(default=None, max_length=50)),
                ('host', models.CharField(default=None, max_length=50)),
                ('port', models.CharField(default=None, max_length=50)),
                ('user', models.CharField(default=None, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('globalapp.common', models.Model),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='favicon',
            field=models.ImageField(default=None, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='logo',
            field=models.ImageField(default=None, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
