# Generated by Django 4.2.11 on 2024-05-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0008_emailconfigure_alter_softwareasset_favicon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfigure',
            old_name='password',
            new_name='email_password',
        ),
    ]
