# Generated by Django 4.2.11 on 2024-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0010_alter_emailconfigure_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfigure',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfigure',
            name='port',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfigure',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
