# Generated by Django 4.2.11 on 2024-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0011_alter_emailconfigure_host_alter_emailconfigure_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareasset',
            name='title',
            field=models.CharField(default='Vitasoft', max_length=50),
        ),
    ]
