# Generated by Django 4.2.11 on 2024-06-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0012_alter_softwareasset_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseBeneficariesModel',
        ),
    ]
