# Generated by Django 4.2.11 on 2024-07-06 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0013_delete_basebeneficariesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBeneficariesModel',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nid_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nid_number', message='NID number must contain only numeric values.', regex='^[0-9]*$')])),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('profile_picture', models.ImageField(default='profile_pictures/profile-picture.jpg', upload_to='profile_pictures/')),
                ('nid_front', models.ImageField(default='nid/nid_front.jpeg', upload_to='nid/')),
                ('nid_back', models.ImageField(default='nid/nid_back.jpeg', upload_to='nid/')),
            ],
            bases=('globalapp.common',),
        ),
    ]
