# Generated by Django 4.2.11 on 2025-09-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0016_common_updated_at_historicalcommon_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcommon',
            name='updated_at',
        ),
    ]
