# Generated by Django 4.2.11 on 2025-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0017_remove_common_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommon',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
