# Generated by Django 4.2.11 on 2025-09-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0017_alter_common_created_at_and_more'),
        ('globalapp', '0019_remove_common_updated_at_and_more'),
    ]

    operations = [
    ]
