# Generated by Django 4.2.11 on 2025-09-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0020_merge_20250905_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcommon',
            name='updated_at',
        ),
    ]
