# Generated by Django 4.2.11 on 2024-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='dummy',
            name='route',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
