# Generated by Django 4.2.11 on 2024-06-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_dummy_content_dummy_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
