# Generated by Django 4.2.11 on 2024-08-31 05:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('cms', '0005_banneritem_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='banneritem',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banneritem',
            name='title',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='banneritem',
            name='button',
            field=models.ManyToManyField(to='cms.button'),
        ),
    ]
