# Generated by Django 4.2.11 on 2024-09-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('cms', '0007_counteritem_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesItem',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities_item', models.ManyToManyField(to='cms.facilitiesitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
