# Generated by Django 4.2.11 on 2024-09-01 09:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_facilitiesitem_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitiesitem',
            name='number',
        ),
        migrations.AddField(
            model_name='facilitiesitem',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
