# Generated by Django 4.2.11 on 2024-09-01 09:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_facilitiesitem_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(default=None)),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
