# Generated by Django 4.2.11 on 2024-09-01 10:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_specialcta_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcta',
            name='description',
            field=ckeditor.fields.RichTextField(default='Input text here..'),
        ),
    ]
