# Generated by Django 4.2.11 on 2024-09-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_specialcta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcta',
            name='button_text',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialcta',
            name='button_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='specialcta',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='specialcta',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
