# Generated by Django 4.2.11 on 2024-09-14 12:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('cms', '0015_faq_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLMS',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=('globalapp.common',),
        ),
    ]
