# Generated by Django 4.2.11 on 2024-08-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('lmsfeatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationStatus',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('title', models.CharField(max_length=200)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='coursecontents',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
