# Generated by Django 4.2.11 on 2024-09-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0002_installationstatus_coursecontents_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='milestones',
            field=models.ManyToManyField(to='lmsfeatures.coursemilestones'),
        ),
    ]
