# Generated by Django 4.2.11 on 2024-09-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0004_payment_enrollcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontents',
            name='installment_status',
            field=models.ManyToManyField(default=None, to='lmsfeatures.installationstatus'),
        ),
    ]
