# Generated by Django 4.2.11 on 2024-09-10 05:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('lmsfeatures', '0005_coursecontents_installment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('qr_image', models.ImageField(upload_to='qr/')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsfeatures.paymentmethods'),
        ),
    ]
