# Generated by Django 4.2.11 on 2024-09-10 05:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0006_paymentmethods_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
