# Generated by Django 4.2.11 on 2024-09-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0007_alter_paymentmethods_qr_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLcommerceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100)),
                ('store_pass', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('sandbox_status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
