# Generated by Django 4.2.11 on 2024-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0008_sslcommercesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationstatus',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
