# Generated by Django 4.2.11 on 2024-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0009_installationstatus_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
