# Generated by Django 4.2.11 on 2024-09-14 11:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0011_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
