# Generated by Django 4.2.11 on 2024-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0012_courses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
