# Generated by Django 4.2.11 on 2025-08-03 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_branch_users_branch'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('globalapp', '0014_basebeneficariesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('purchase_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_status', models.CharField(max_length=20)),
                ('vendor_cheque_details', models.TextField(blank=True, null=True)),
                ('branch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='users.branch')),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='contacts.contact')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('sale_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_status', models.CharField(max_length=20)),
                ('loan_period', models.IntegerField(blank=True, null=True)),
                ('first_time_down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('emi_start_date', models.DateField(blank=True, null=True)),
                ('emi_end_date', models.DateField(blank=True, null=True)),
                ('branch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='users.branch')),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='contacts.contact')),
                ('manager_user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sales', to=settings.AUTH_USER_MODEL)),
                ('supervisor_user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sales', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('imei_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='products.product')),
                ('sale_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.sale')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('return_date', models.DateField()),
                ('purchase_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='transactions.purchase')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='products.product')),
                ('purchase_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.purchase')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contacts.contact')),
                ('sale_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.sale')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('cheque_number', models.CharField(max_length=100)),
                ('cheque_status', models.CharField(max_length=20)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='contacts.contact')),
                ('loan_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='transactions.sale')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('affiliate_status', models.CharField(max_length=20)),
                ('affiliate_user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to=settings.AUTH_USER_MODEL)),
                ('sale_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='transactions.sale')),
            ],
            bases=('globalapp.common',),
        ),
    ]
