# Generated by Django 4.2.11 on 2025-08-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['-id'], 'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='imei_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='IMEI Number'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
