# Generated by Django 4.2.11 on 2025-08-13 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_alter_customergroup_options_and_more'),
        ('users', '0010_branch_users_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_branchproductstock_options_alter_brand_options_and_more'),
        ('transactions', '0002_alter_saleitem_options_alter_saleitem_imei_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatecommission',
            options={'ordering': ['-id'], 'verbose_name': 'Affiliate Commission', 'verbose_name_plural': 'Affiliate Commissions'},
        ),
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['-id'], 'verbose_name': 'Cheque', 'verbose_name_plural': 'Cheques'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['-id'], 'verbose_name': 'Purchase Item', 'verbose_name_plural': 'Purchase Items'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-return_date'], 'verbose_name': 'Purchase Return', 'verbose_name_plural': 'Purchase Returns'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='affiliate_status',
            field=models.CharField(max_length=20, verbose_name='Affiliate Status'),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='affiliate_user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Affiliate User'),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Commission Amount'),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='sale_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='transactions.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_number',
            field=models.CharField(max_length=100, verbose_name='Cheque Number'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_status',
            field=models.CharField(max_length=20, verbose_name='Cheque Status'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='contacts.contact', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='loan_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='transactions.sale', verbose_name='Loan Sale'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contacts.contact', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(max_length=20, verbose_name='Purchase Status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='contacts.contact', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor_cheque_details',
            field=models.TextField(blank=True, null=True, verbose_name='Vendor Cheque Details'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.purchase', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='purchase_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='transactions.purchase', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date',
            field=models.DateField(verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='contacts.contact', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='emi_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='EMI End Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='emi_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='EMI Start Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='first_time_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='First Time Down Payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='loan_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Loan Period (Months)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='manager_user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sales', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_status',
            field=models.CharField(max_length=20, verbose_name='Sale Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='supervisor_user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sales', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount'),
        ),
    ]
