# Generated by Django 4.2.11 on 2025-08-15 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_customer_account_balance_and_more'),
        ('globalapp', '0015_historicalcommon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_historicalsaleitem_historicalsale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentType',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Installment Type',
                'verbose_name_plural': 'Installment Types',
                'ordering': ['type'],
            },
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('behaviour_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ['name'],
            },
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('installment_date', models.DateField(verbose_name='Installment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('installment_status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], max_length=10, verbose_name='Status')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.customer', verbose_name='Customer')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['-installment_date'],
            },
            bases=('globalapp.common',),
        ),
    ]
