# Generated by Django 4.2.11 on 2025-08-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0015_historicalcommon'),
        ('contacts', '0005_customer_account_balance_and_more'),
        ('transactions', '0006_installmenttype_loantype_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('receive_type', models.CharField(choices=[('cash', 'Cash'), ('product', 'Product')], max_length=20, verbose_name='Receive Type')),
                ('product_details', models.JSONField(blank=True, null=True, verbose_name='Product Details')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('pay_from_account', models.BooleanField(default=False, verbose_name='Pay From Account')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.customer', verbose_name='Customer Name')),
                ('installment', models.ManyToManyField(blank=True, to='transactions.installment', verbose_name='Installments')),
                ('installment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.installmenttype', verbose_name='Installment Type')),
                ('loan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.loantype', verbose_name='Loan Type')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
            bases=('globalapp.common',),
        ),
    ]
