# Generated by Django 4.2.11 on 2025-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='behaviour_type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
