# Generated by Django 4.2.11 on 2025-09-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_historicalloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstallmenttype',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Duration'),
        ),
        migrations.AddField(
            model_name='installmenttype',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Duration'),
        ),
    ]
