# Generated by Django 4.2.11 on 2025-09-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_historicalinstallmenttype_total_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinstallmenttype',
            old_name='amount',
            new_name='instalment_cullect',
        ),
        migrations.RenameField(
            model_name='installmenttype',
            old_name='amount',
            new_name='instalment_cullect',
        ),
    ]
