# Generated by Django 4.2.11 on 2025-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_rename_amount_historicalinstallmenttype_instalment_cullect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
