# Generated by Django 4.2.11 on 2025-09-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_remove_loan_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalaffiliatecommission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcheque',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalinstallmenttype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalloan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalpurchaseitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasereturn',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalsaleitem',
            name='updated_at',
        ),
    ]
