# Generated by Django 4.2.11 on 2025-09-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_remove_historicalaffiliatecommission_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
