# Generated by Django 4.2.11 on 2025-09-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_historicalloan_updated_at_loan_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='first_down_payment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='first_down_payment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
