# Generated by Django 4.2.11 on 2025-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_historicalloan_first_down_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstallmenttype',
            name='instalment_cullect',
            field=models.IntegerField(verbose_name='instalment_cullect_duration'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='first_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='First Down Payment'),
        ),
        migrations.AlterField(
            model_name='installmenttype',
            name='instalment_cullect',
            field=models.IntegerField(verbose_name='instalment_cullect_duration'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='first_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='First Down Payment'),
        ),
    ]
