# Generated by Django 4.2.11 on 2025-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_alter_historicalinstallmenttype_instalment_cullect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstallmenttype',
            name='instalment_cullect',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='installmenttype',
            name='instalment_cullect',
            field=models.IntegerField(verbose_name='Amount'),
        ),
    ]
