# Generated by Django 4.2.11 on 2025-09-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_area_parent_branch_historicalarea_parent_branch_and_more'),
        ('transactions', '0024_alter_historicalinstallmenttype_instalment_cullect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='area_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='branch_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='installment',
            name='area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='installment',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='loan',
            name='area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_area_set', to='users.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='loan',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_branch_set', to='users.branch', verbose_name='Branch'),
        ),
    ]
