# Generated by Django 4.2.11 on 2025-09-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_historicalloan_area_name_historicalloan_branch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloan',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='historicalloan',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='branch_name',
        ),
    ]
