# Generated by Django 4.2.11 on 2025-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_historicalloan_area_name_historicalloan_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='loan_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
