# Generated by Django 4.2.11 on 2025-09-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_historicalusers_area_users_area_alter_area_area_staf'),
        ('transactions', '0028_installment_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='loan_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_types', to='users.branch', verbose_name='Branch'),
        ),
    ]
