# Generated by Django 4.2.11 on 2025-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_loantype_loan_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='installment_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Installment Pay'),
        ),
    ]
