# Generated by Django 4.2.11 on 2025-10-23 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        ('users', '0021_alter_users_profile_picture'),
        ('contacts', '0021_alter_customergroup_group_leader_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0030_installment_installment_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments_areas', to='users.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments_branches', to='users.branch', verbose_name='Branch'),
        ),
        migrations.CreateModel(
            name='DailySaving',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('area_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailysavings_areas', to='users.area', verbose_name='Area')),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailysavings_branches', to='users.branch', verbose_name='Branch')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.customer', verbose_name='Customer')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
            ],
            options={
                'verbose_name': 'DailySaving',
                'verbose_name_plural': 'DailySavings',
                'ordering': ['amount'],
            },
            bases=('globalapp.common',),
        ),
    ]
