# Generated by Django 4.2.11 on 2025-10-23 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0021_alter_customergroup_group_leader_user'),
        ('transactions', '0031_alter_installment_area_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('transection_type', models.CharField(choices=[('cashin', 'Cash In'), ('cashout', 'Cash Out')], max_length=10, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('modelname', models.CharField(max_length=200)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.customer', verbose_name='Customer Name')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
            ],
            bases=('globalapp.common',),
        ),
    ]
