# Generated by Django 4.2.11 on 2025-10-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_transection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='modelname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Model Name'),
        ),
    ]
