# Generated by Django 4.2.11 on 2025-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_alter_transection_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='pay_from_account',
            field=models.BooleanField(default=False, verbose_name='Pay From Account'),
        ),
    ]
