# Generated by Django 4.2.11 on 2025-10-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_customertype_customer_coustomer_type_and_more'),
        ('users', '0021_alter_users_profile_picture'),
        ('transactions', '0034_installment_pay_from_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.area', verbose_name='Area Name'),
        ),
        migrations.AddField(
            model_name='transection',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.branch', verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='transection',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customergroup', verbose_name='Customer Group'),
        ),
    ]
