# Generated by Django 4.2.11 on 2025-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_transection_area_name_transection_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Due Amount'),
        ),
    ]
