# Generated by Django 4.2.11 on 2025-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_installment_due_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='DueAmount'),
        ),
        migrations.AddField(
            model_name='transection',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='PaidAmount'),
        ),
    ]
