# Generated by Django 4.2.11 on 2025-11-03 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_users_mult_branch'),
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0037_transection_due_amount_transection_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Due Amount'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Amount'),
        ),
        migrations.CreateModel(
            name='HistoricalBranchAccount',
            fields=[
                ('common_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='globalapp.common')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('hand_cash', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Hand Cash')),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Collection')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.branch', verbose_name='Branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report_submitted_by_user_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Report Submitted By')),
            ],
            options={
                'verbose_name': 'historical BranchAccount',
                'verbose_name_plural': 'historical BranchAccount',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BranchAccount',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('hand_cash', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Hand Cash')),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Collection')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch', verbose_name='Branch')),
                ('report_submitted_by_user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Report Submitted By')),
            ],
            options={
                'verbose_name': 'BranchAccount',
                'verbose_name_plural': 'BranchAccount',
                'ordering': ['-date'],
            },
            bases=('globalapp.common',),
        ),
    ]
