# Generated by Django 4.2.11 on 2026-01-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        ('users', '0024_alter_users_mult_branch'),
        ('transactions', '0038_alter_transection_due_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('title', models.CharField(max_length=20, verbose_name='Title Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('area_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downPayments_areas', to='users.area', verbose_name='Area')),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downPayments_branches', to='users.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Down Payment',
                'verbose_name_plural': 'Down Payments',
                'ordering': ['amount'],
            },
            bases=('globalapp.common',),
        ),
    ]
