# Generated by Django 4.2.11 on 2026-01-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_users_mult_branch'),
        ('transactions', '0039_downpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downpayment',
            options={'verbose_name': 'Down Payment', 'verbose_name_plural': 'Down Payments'},
        ),
        migrations.RemoveField(
            model_name='downpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='historicalloan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='downpayment',
            name='amount_or_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Amount / Percentage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downpayment',
            name='ispercentage',
            field=models.BooleanField(default=False, verbose_name='Is Percentage'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='downpayment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.downpayment', verbose_name='Down Payment Rule'),
        ),
        migrations.AddField(
            model_name='loan',
            name='downpayment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_downpayments', to='transactions.downpayment', verbose_name='Down Payment Rule'),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downpayment_area_set', to='users.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downpayment_branch_set', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title Name'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan Amount'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan Amount'),
        ),
    ]
