# Generated by Django 4.2.11 on 2026-01-14 08:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_alter_downpayment_options_remove_downpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='updated_at',
            field=models.DateTimeField(
                blank=True,
                default=timezone.now,
                editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
