# Generated by Django 4.2.11 on 2026-01-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_branchproductstock_options_and_more'),
        ('transactions', '0041_historicalloan_updated_at_loan_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpurchase',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical purchase', 'verbose_name_plural': 'historical purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='purchase_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='purchase_product_variation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.variation', verbose_name='Variation'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_product_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variation', verbose_name='Variation'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='purchase_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='vendor_cheque_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor_cheque_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
