# Generated by Django 4.2.11 on 2026-01-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_alter_historicalpurchase_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='installment',
        ),
    ]
