# Generated by Django 4.2.11 on 2026-01-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_unick_key1_alter_unick_key2'),
        ('transactions', '0044_loan_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unickkey',
            field=models.ManyToManyField(blank=True, to='products.unick'),
        ),
    ]
