# Generated by Django 4.2.11 on 2026-01-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_purchase_unickkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='installment',
        ),
    ]
