# Generated by Django 4.2.11 on 2026-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_remove_loan_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment',
            field=models.ManyToManyField(blank=True, to='transactions.installment'),
        ),
    ]
