# Generated by Django 4.2.11 on 2026-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_loan_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloan',
            name='first_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='pay_from_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='first_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='pay_from_account',
            field=models.BooleanField(default=False),
        ),
    ]
