# Generated by Django 4.2.11 on 2026-02-28 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_branchproductstock_options_and_more'),
        ('transactions', '0048_alter_historicalloan_first_down_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpurchaseitem',
            old_name='product_name',
            new_name='purchase_product',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='purchase_product',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='purchase_product_variation',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='historicalpurchaseitem',
            name='purchase_name',
        ),
        migrations.RemoveField(
            model_name='historicalpurchaseitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='historicalpurchaseitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_product_variation',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unickkey',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_name',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='purchase_product_variation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.variation', verbose_name='Variation'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaseitem',
            field=models.ManyToManyField(to='transactions.purchaseitem'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_product_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variation', verbose_name='Variation'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unickkey',
            field=models.ManyToManyField(blank=True, to='products.unick'),
        ),
    ]
