# Generated by Django 4.2.11 on 2026-03-10 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_historicalusers_nid_back_alter_users_nid_back'),
        ('contacts', '0023_customer_received_by_historicalcustomer_received_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0049_rename_product_name_historicalpurchaseitem_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstallmenttype',
            name='total_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Duration'),
        ),
        migrations.AlterField(
            model_name='installmenttype',
            name='total_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Duration'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchaseitem',
            field=models.ManyToManyField(blank=True, to='transactions.purchaseitem'),
        ),
        migrations.CreateModel(
            name='CollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.area')),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.branch')),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customergroup')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
