# Generated by Django 4.2.11 on 2026-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0050_alter_historicalinstallmenttype_total_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstallmenttype',
            name='instalment_cullect',
            field=models.IntegerField(verbose_name='Installment Collect Gap'),
        ),
        migrations.AlterField(
            model_name='historicalinstallmenttype',
            name='total_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Duration'),
        ),
        migrations.AlterField(
            model_name='installmenttype',
            name='instalment_cullect',
            field=models.IntegerField(verbose_name='Installment Collect Gap'),
        ),
        migrations.AlterField(
            model_name='installmenttype',
            name='total_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Duration'),
        ),
    ]
