# Generated by Django 4.2.11 on 2026-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0051_alter_historicalinstallmenttype_instalment_cullect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstallmenttype',
            name='total_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Duration'),
        ),
        migrations.AlterField(
            model_name='installmenttype',
            name='total_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Duration'),
        ),
    ]
