# Generated by Django 4.2.11 on 2026-03-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0052_alter_historicalinstallmenttype_total_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='installment',
        ),
    ]
