# Generated by Django 4.2.11 on 2026-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0053_remove_loan_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment',
            field=models.ManyToManyField(blank=True, to='transactions.installment'),
        ),
    ]
