# Generated by Django 4.2.11 on 2026-03-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_customer_received_by_historicalcustomer_received_by'),
        ('transactions', '0054_loan_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='customergroup_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.customergroup'),
        ),
        migrations.AddField(
            model_name='installment',
            name='customergroup_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.customergroup'),
        ),
        migrations.AddField(
            model_name='loan',
            name='customergroup_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.customergroup'),
        ),
    ]
