# Generated by Django 4.2.11 on 2026-03-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_customer_received_by_historicalcustomer_received_by'),
        ('transactions', '0055_historicalloan_customergroup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaving',
            name='customergroup_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.customergroup'),
        ),
    ]
