# Generated by Django 4.2.11 on 2026-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_brand_options_alter_category_options_and_more'),
        ('transactions', '0057_historicalloan_received_by_loan_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unickkey',
            field=models.ManyToManyField(blank=True, to='products.unick', verbose_name='Unique Identifiers'),
        ),
    ]
