# Generated by Django 4.2.11 on 2025-08-03 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('products', '0001_initial'),
        ('globalapp', '0014_basebeneficariesmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_branch_users_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCheque',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('cheque_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vndcq_status', models.CharField(max_length=20)),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('transfer_date', models.DateField()),
                ('stc_status', models.CharField(max_length=20)),
                ('from_branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='users.branch')),
                ('to_branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='users.branch')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('quantity_adjusted', models.IntegerField()),
                ('reason', models.TextField()),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('request_date', models.DateField()),
                ('repair_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('requested_by_user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('expense_category', models.CharField(max_length=50)),
                ('voucher_image_url', models.URLField(blank=True, null=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Daybook',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('date', models.DateField(unique=True)),
                ('hand_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_transfer_to_ho', models.DecimalField(decimal_places=2, max_digits=15)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('report_submitted_by_user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('globalapp.common',),
        ),
    ]
