# Generated by Django 4.2.11 on 2025-08-13 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_alter_customergroup_options_and_more'),
        ('users', '0010_branch_users_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('inventory_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daybook',
            options={'ordering': ['-date'], 'verbose_name': 'Daybook', 'verbose_name_plural': 'Daybooks'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='repairrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'Repair Request', 'verbose_name_plural': 'Repair Requests'},
        ),
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-id'], 'verbose_name': 'Stock Adjustment', 'verbose_name_plural': 'Stock Adjustments'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-transfer_date'], 'verbose_name': 'Stock Transfer', 'verbose_name_plural': 'Stock Transfers'},
        ),
        migrations.AlterModelOptions(
            name='vendorcheque',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Vendor Cheque', 'verbose_name_plural': 'Vendor Cheques'},
        ),
        migrations.AlterField(
            model_name='daybook',
            name='bank_transfer_to_ho',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bank Transfer to HO'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='hand_cash',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Hand Cash'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='report_submitted_by_user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Report Submitted By'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='total_collection',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Collection'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Expenses'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(max_length=50, verbose_name='Expense Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='voucher_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Voucher Image URL'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='repair_status',
            field=models.CharField(max_length=20, verbose_name='Repair Status'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='request_date',
            field=models.DateField(verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='requested_by_user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_adjusted',
            field=models.IntegerField(verbose_name='Quantity Adjusted'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.TextField(verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='users.branch', verbose_name='From Branch'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='stc_status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='users.branch', verbose_name='To Branch'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_date',
            field=models.DateField(verbose_name='Transfer Date'),
        ),
        migrations.AlterField(
            model_name='vendorcheque',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='vendorcheque',
            name='cheque_number',
            field=models.CharField(max_length=100, verbose_name='Cheque Number'),
        ),
        migrations.AlterField(
            model_name='vendorcheque',
            name='issue_date',
            field=models.DateField(verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='vendorcheque',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='vendorcheque',
            name='vndcq_status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
    ]
