# Generated by Django 4.2.11 on 2025-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_finance', '0003_historicalvendorcheque_historicalstocktransfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='voucher_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='voucher_images/', verbose_name='Voucher Image URL'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='voucher_image_url',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Voucher Image URL'),
        ),
    ]
