# Generated by Django 4.2.11 on 2025-09-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_finance', '0005_historicaldaybook_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldaybook',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalrepairrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalstockadjustment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalstocktransfer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalvendorcheque',
            name='updated_at',
        ),
    ]
