# Generated by Django 4.2.11 on 2026-01-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_branchproductstock_product_name_and_more'),
        ('inventory_finance', '0009_remove_historicaldaybook_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={},
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='stc_status',
            field=models.CharField(default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='HistoricalStockTransfer',
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory_finance.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='unickkeys',
            field=models.ManyToManyField(blank=True, to='products.unick'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variation'),
        ),
    ]
