# Generated by Django 4.2.11 on 2026-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_branchproductstock_product_name_and_more'),
        ('inventory_finance', '0010_stocktransferline_alter_stocktransfer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-transfer_date'], 'verbose_name_plural': 'Stock Transfers'},
        ),
        migrations.AlterModelOptions(
            name='stocktransferline',
            options={'ordering': ['id'], 'verbose_name_plural': 'Stock Transfer Lines'},
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='is_applied',
            field=models.BooleanField(default=False, editable=False, help_text='Automatically set to True when transfer is applied'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='stc_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='unickkeys',
            field=models.ManyToManyField(blank=True, help_text='For unique variations: select the specific units to transfer', to='products.unick'),
        ),
    ]
