# Generated by Django 4.2.11 on 2026-02-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_branchproductstock_options_and_more'),
        ('inventory_finance', '0011_alter_stocktransfer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stocktransferline',
            options={},
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='is_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='stc_status',
            field=models.CharField(default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='unickkeys',
            field=models.ManyToManyField(blank=True, to='products.unick'),
        ),
    ]
