# Generated by Django 4.2.11 on 2024-04-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_phone_ben_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='name',
            new_name='contact_name',
        ),
    ]
