# Generated by Django 4.2.11 on 2024-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_rename_name_phone_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
