# Generated by Django 4.2.11 on 2025-08-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('users', '0010_branch_users_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='SellingPriceGroup',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=100)),
                ('price_multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], max_length=10)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=100)),
                ('sku_suffix', models.CharField(max_length=50)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warranty'),
        ),
        migrations.CreateModel(
            name='BranchProductStock',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('quantity', models.IntegerField()),
                ('opening_stock', models.IntegerField()),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            bases=('globalapp.common',),
        ),
    ]
