# Generated by Django 4.2.11 on 2025-08-13 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_branch_users_branch'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchproductstock',
            options={'ordering': ['product_name'], 'verbose_name': 'Branch Product Stock', 'verbose_name_plural': 'Branch Product Stocks'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='sellingpricegroup',
            options={'ordering': ['name'], 'verbose_name': 'Selling Price Group', 'verbose_name_plural': 'Selling Price Groups'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['name'], 'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ['name'], 'verbose_name': 'Warranty', 'verbose_name_plural': 'Warranties'},
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='opening_stock',
            field=models.IntegerField(verbose_name='Opening Stock'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warranty', verbose_name='Warranty'),
        ),
        migrations.AlterField(
            model_name='sellingpricegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Price Group Name'),
        ),
        migrations.AlterField(
            model_name='sellingpricegroup',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Multiplier'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Unit Name'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Variation Name'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku_suffix',
            field=models.CharField(max_length=50, verbose_name='SKU Suffix'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration_type',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], max_length=10, verbose_name='Duration Type'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Warranty Name'),
        ),
    ]
