# Generated by Django 4.2.11 on 2025-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_branchproductstock_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='Thumbnail Image'),
        ),
    ]
