# Generated by Django 4.2.11 on 2026-01-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        ('products', '0003_product_price_product_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationAttribute',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Variation specific price', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price (default)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warranty'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku_suffix',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration_type',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], max_length=10),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='VariationAttributeValue',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('value', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationattribute')),
                ('variation_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.variation')),
            ],
            bases=('globalapp.common',),
        ),
    ]
