# Generated by Django 4.2.11 on 2026-01-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_variationattribute_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='variationattribute',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='variation',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variationattribute',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warranty'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku_suffix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='variationattributevalue',
            name='value',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='variationattributevalue',
            unique_together={('variation_ref', 'attribute')},
        ),
    ]
