# Generated by Django 4.2.11 on 2026-01-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_users_mult_branch'),
        ('products', '0005_alter_variation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchproductstock',
            options={'ordering': ['product_variation']},
        ),
        migrations.RenameField(
            model_name='branchproductstock',
            old_name='branch_name',
            new_name='stock_branch',
        ),
        migrations.AddField(
            model_name='branchproductstock',
            name='product_variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.variation', verbose_name='Variation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='branchproductstock',
            unique_together={('product_variation', 'stock_branch')},
        ),
        migrations.RemoveField(
            model_name='branchproductstock',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='branchproductstock',
            name='product_name',
        ),
    ]
