# Generated by Django 4.2.11 on 2026-01-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_branchproductstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchproductstock',
            options={},
        ),
        migrations.AddField(
            model_name='branchproductstock',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
