# Generated by Django 4.2.11 on 2026-01-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0021_remove_common_updated_at_and_more'),
        ('products', '0007_alter_branchproductstock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='unick',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('key1', models.CharField(max_length=100)),
                ('key2', models.CharField(max_length=100)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.AddField(
            model_name='variation',
            name='isunck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='unickkey',
            field=models.ManyToManyField(blank=True, to='products.unick'),
        ),
    ]
