# Generated by Django 4.2.11 on 2026-01-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_unick_variation_isunck_variation_unickkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unick',
            name='key1',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unick',
            name='key2',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
