# Generated by Django 4.2.11 on 2026-01-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_users_mult_branch'),
        ('products', '0010_branchproductstock_unickkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchproductstock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.variation'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='stock_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
    ]
