# Generated by Django 4.2.11 on 2026-02-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_historicalusers_nid_back_alter_users_nid_back'),
        ('products', '0011_alter_branchproductstock_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchproductstock',
            options={'ordering': ['stock_branch', 'product_name'], 'verbose_name_plural': 'Branch Product Stocks'},
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.product'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity in this branch'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='stock_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='unickkey',
            field=models.ManyToManyField(blank=True, help_text='Individual units for unique variations', to='products.unick'),
        ),
    ]
