# Generated by Django 4.2.11 on 2026-02-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_historicalusers_nid_back_alter_users_nid_back'),
        ('products', '0012_alter_branchproductstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchproductstock',
            options={},
        ),
        migrations.AddField(
            model_name='variation',
            name='dealer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='stock_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='unickkey',
            field=models.ManyToManyField(blank=True, to='products.unick'),
        ),
    ]
