# Generated by Django 4.2.11 on 2026-03-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_historicalusers_nid_back_alter_users_nid_back'),
        ('products', '0013_alter_branchproductstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='unick',
            options={'ordering': ['id'], 'verbose_name': 'Unique Key', 'verbose_name_plural': 'Unique Keys'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['id'], 'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AlterModelOptions(
            name='variationattribute',
            options={'ordering': ['order'], 'verbose_name': 'Variation Attribute', 'verbose_name_plural': 'Variation Attributes'},
        ),
        migrations.AlterModelOptions(
            name='variationattributevalue',
            options={'ordering': ['id'], 'verbose_name': 'Variation Attribute Value', 'verbose_name_plural': 'Variation Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ['name'], 'verbose_name': 'Warranty', 'verbose_name_plural': 'Warranties'},
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_stocks', to='products.product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.variation', verbose_name='Product Variation'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='stock_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_stocks', to='users.branch', verbose_name='Stock Branch'),
        ),
        migrations.AlterField(
            model_name='branchproductstock',
            name='unickkey',
            field=models.ManyToManyField(blank=True, related_name='branch_product_stocks', to='products.unick', verbose_name='Unique Keys'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Product Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Product SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.unit', verbose_name='Unit Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.warranty', verbose_name='Product Warranty'),
        ),
        migrations.AlterField(
            model_name='unick',
            name='key1',
            field=models.CharField(max_length=100, unique=True, verbose_name='IMI-1'),
        ),
        migrations.AlterField(
            model_name='unick',
            name='key2',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='IMI-2'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Unit Name'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='dealer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dealer Price'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='isunck',
            field=models.BooleanField(default=False, verbose_name='Has Unique Key'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Variation Name'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku_suffix',
            field=models.CharField(blank=True, max_length=50, verbose_name='SKU Suffix'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='unickkey',
            field=models.ManyToManyField(blank=True, related_name='variations', to='products.unick', verbose_name='Unique Keys'),
        ),
        migrations.AlterField(
            model_name='variationattribute',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Attribute Name'),
        ),
        migrations.AlterField(
            model_name='variationattribute',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='variationattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_values', to='products.variationattribute', verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='variationattributevalue',
            name='value',
            field=models.CharField(max_length=150, verbose_name='Attribute Value'),
        ),
        migrations.AlterField(
            model_name='variationattributevalue',
            name='variation_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.variation', verbose_name='Variation'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration_type',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], max_length=10, verbose_name='Duration Type'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Warranty Name'),
        ),
    ]
